# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "sourcebreaker"
languages = ["C", "CXX"]
cmake-after = """
# Enable multi-core compilation universally
set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /MP")
set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /MP")
"""

[variables]
SAFETYHOOK_FETCH_ZYDIS = "ON"

# [vcpkg]
# version = "2025.01.13"
# packages = [""]

[fetch-content]
safetyhook = { git = "https://github.com/cursey/safetyhook", tag = "v0.5.4" }

[target.memtools]
type = "static"
compile-features = ["cxx_std_23"]
sources = ["src/memtools/**.cpp"]
headers = ["src/memtools/**.hpp"]

link-libraries = ["safetyhook::safetyhook"]

[target.tfsdk]
type = "static"
compile-features = ["cxx_std_23"]
sources = ["src/tfsdk/**.cpp"]
headers = ["src/tfsdk/**.hpp"]

include-directories = ["src/"]

[target.sourcebreaker]
type = "shared"
compile-features = ["cxx_std_23"]
sources = ["src/sourcebreaker/**.cpp"]
headers = ["src/sourcebreaker/**.hpp"]

link-libraries = ["memtools", "tfsdk"]
include-directories = ["src/"]

[target.mapper]
type = "executable"
compile-features = ["cxx_std_23"]
sources = ["src/mapper/**.cpp"]
headers = ["src/mapper/**.hpp"]
